# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/paulfajar/Documents/Grafika Komputer/Praktikum2"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/paulfajar/Documents/Grafika Komputer/Praktikum2"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/paulfajar/Documents/Grafika Komputer/Praktikum2/CMakeFiles" "/Users/paulfajar/Documents/Grafika Komputer/Praktikum2//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/paulfajar/Documents/Grafika Komputer/Praktikum2/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named OpenGLSetup

# Build rule for target.
OpenGLSetup: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 OpenGLSetup
.PHONY : OpenGLSetup

# fast build rule for target.
OpenGLSetup/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenGLSetup.dir/build.make CMakeFiles/OpenGLSetup.dir/build
.PHONY : OpenGLSetup/fast

#=============================================================================
# Target rules for targets named Exercise1

# Build rule for target.
Exercise1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Exercise1
.PHONY : Exercise1

# fast build rule for target.
Exercise1/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Exercise1.dir/build.make CMakeFiles/Exercise1.dir/build
.PHONY : Exercise1/fast

#=============================================================================
# Target rules for targets named Exercise2

# Build rule for target.
Exercise2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Exercise2
.PHONY : Exercise2

# fast build rule for target.
Exercise2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Exercise2.dir/build.make CMakeFiles/Exercise2.dir/build
.PHONY : Exercise2/fast

#=============================================================================
# Target rules for targets named Exercise3

# Build rule for target.
Exercise3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Exercise3
.PHONY : Exercise3

# fast build rule for target.
Exercise3/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Exercise3.dir/build.make CMakeFiles/Exercise3.dir/build
.PHONY : Exercise3/fast

#=============================================================================
# Target rules for targets named ShaderExercise1

# Build rule for target.
ShaderExercise1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ShaderExercise1
.PHONY : ShaderExercise1

# fast build rule for target.
ShaderExercise1/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ShaderExercise1.dir/build.make CMakeFiles/ShaderExercise1.dir/build
.PHONY : ShaderExercise1/fast

#=============================================================================
# Target rules for targets named ShaderExercise2

# Build rule for target.
ShaderExercise2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ShaderExercise2
.PHONY : ShaderExercise2

# fast build rule for target.
ShaderExercise2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ShaderExercise2.dir/build.make CMakeFiles/ShaderExercise2.dir/build
.PHONY : ShaderExercise2/fast

#=============================================================================
# Target rules for targets named ShaderExercise3

# Build rule for target.
ShaderExercise3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ShaderExercise3
.PHONY : ShaderExercise3

# fast build rule for target.
ShaderExercise3/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ShaderExercise3.dir/build.make CMakeFiles/ShaderExercise3.dir/build
.PHONY : ShaderExercise3/fast

#=============================================================================
# Target rules for targets named TransformMain

# Build rule for target.
TransformMain: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TransformMain
.PHONY : TransformMain

# fast build rule for target.
TransformMain/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TransformMain.dir/build.make CMakeFiles/TransformMain.dir/build
.PHONY : TransformMain/fast

#=============================================================================
# Target rules for targets named TransformExercise1

# Build rule for target.
TransformExercise1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TransformExercise1
.PHONY : TransformExercise1

# fast build rule for target.
TransformExercise1/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TransformExercise1.dir/build.make CMakeFiles/TransformExercise1.dir/build
.PHONY : TransformExercise1/fast

#=============================================================================
# Target rules for targets named TransformExercise2

# Build rule for target.
TransformExercise2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TransformExercise2
.PHONY : TransformExercise2

# fast build rule for target.
TransformExercise2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TransformExercise2.dir/build.make CMakeFiles/TransformExercise2.dir/build
.PHONY : TransformExercise2/fast

#=============================================================================
# Target rules for targets named TextureMain

# Build rule for target.
TextureMain: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TextureMain
.PHONY : TextureMain

# fast build rule for target.
TextureMain/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextureMain.dir/build.make CMakeFiles/TextureMain.dir/build
.PHONY : TextureMain/fast

#=============================================================================
# Target rules for targets named TextureExercise1

# Build rule for target.
TextureExercise1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TextureExercise1
.PHONY : TextureExercise1

# fast build rule for target.
TextureExercise1/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextureExercise1.dir/build.make CMakeFiles/TextureExercise1.dir/build
.PHONY : TextureExercise1/fast

#=============================================================================
# Target rules for targets named TextureExercise2

# Build rule for target.
TextureExercise2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TextureExercise2
.PHONY : TextureExercise2

# fast build rule for target.
TextureExercise2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextureExercise2.dir/build.make CMakeFiles/TextureExercise2.dir/build
.PHONY : TextureExercise2/fast

#=============================================================================
# Target rules for targets named TextureExercise3

# Build rule for target.
TextureExercise3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TextureExercise3
.PHONY : TextureExercise3

# fast build rule for target.
TextureExercise3/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextureExercise3.dir/build.make CMakeFiles/TextureExercise3.dir/build
.PHONY : TextureExercise3/fast

#=============================================================================
# Target rules for targets named TextureExercise4

# Build rule for target.
TextureExercise4: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TextureExercise4
.PHONY : TextureExercise4

# fast build rule for target.
TextureExercise4/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextureExercise4.dir/build.make CMakeFiles/TextureExercise4.dir/build
.PHONY : TextureExercise4/fast

#=============================================================================
# Target rules for targets named CoordinateSystemsMain

# Build rule for target.
CoordinateSystemsMain: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CoordinateSystemsMain
.PHONY : CoordinateSystemsMain

# fast build rule for target.
CoordinateSystemsMain/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoordinateSystemsMain.dir/build.make CMakeFiles/CoordinateSystemsMain.dir/build
.PHONY : CoordinateSystemsMain/fast

#=============================================================================
# Target rules for targets named CoordinateSystemsExercise1

# Build rule for target.
CoordinateSystemsExercise1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CoordinateSystemsExercise1
.PHONY : CoordinateSystemsExercise1

# fast build rule for target.
CoordinateSystemsExercise1/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoordinateSystemsExercise1.dir/build.make CMakeFiles/CoordinateSystemsExercise1.dir/build
.PHONY : CoordinateSystemsExercise1/fast

#=============================================================================
# Target rules for targets named CoordinateSystemsExercise2

# Build rule for target.
CoordinateSystemsExercise2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CoordinateSystemsExercise2
.PHONY : CoordinateSystemsExercise2

# fast build rule for target.
CoordinateSystemsExercise2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoordinateSystemsExercise2.dir/build.make CMakeFiles/CoordinateSystemsExercise2.dir/build
.PHONY : CoordinateSystemsExercise2/fast

#=============================================================================
# Target rules for targets named CoordinateSystemsExercise3

# Build rule for target.
CoordinateSystemsExercise3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CoordinateSystemsExercise3
.PHONY : CoordinateSystemsExercise3

# fast build rule for target.
CoordinateSystemsExercise3/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoordinateSystemsExercise3.dir/build.make CMakeFiles/CoordinateSystemsExercise3.dir/build
.PHONY : CoordinateSystemsExercise3/fast

#=============================================================================
# Target rules for targets named CameraMain

# Build rule for target.
CameraMain: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CameraMain
.PHONY : CameraMain

# fast build rule for target.
CameraMain/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CameraMain.dir/build.make CMakeFiles/CameraMain.dir/build
.PHONY : CameraMain/fast

#=============================================================================
# Target rules for targets named CameraExercise1

# Build rule for target.
CameraExercise1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CameraExercise1
.PHONY : CameraExercise1

# fast build rule for target.
CameraExercise1/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CameraExercise1.dir/build.make CMakeFiles/CameraExercise1.dir/build
.PHONY : CameraExercise1/fast

#=============================================================================
# Target rules for targets named CameraExercise2

# Build rule for target.
CameraExercise2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CameraExercise2
.PHONY : CameraExercise2

# fast build rule for target.
CameraExercise2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CameraExercise2.dir/build.make CMakeFiles/CameraExercise2.dir/build
.PHONY : CameraExercise2/fast

#=============================================================================
# Target rules for targets named TugasPersegi

# Build rule for target.
TugasPersegi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TugasPersegi
.PHONY : TugasPersegi

# fast build rule for target.
TugasPersegi/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TugasPersegi.dir/build.make CMakeFiles/TugasPersegi.dir/build
.PHONY : TugasPersegi/fast

#=============================================================================
# Target rules for targets named BasicLightingMain

# Build rule for target.
BasicLightingMain: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BasicLightingMain
.PHONY : BasicLightingMain

# fast build rule for target.
BasicLightingMain/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BasicLightingMain.dir/build.make CMakeFiles/BasicLightingMain.dir/build
.PHONY : BasicLightingMain/fast

#=============================================================================
# Target rules for targets named BasicLightingExercise1

# Build rule for target.
BasicLightingExercise1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BasicLightingExercise1
.PHONY : BasicLightingExercise1

# fast build rule for target.
BasicLightingExercise1/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BasicLightingExercise1.dir/build.make CMakeFiles/BasicLightingExercise1.dir/build
.PHONY : BasicLightingExercise1/fast

#=============================================================================
# Target rules for targets named BasicLightingExercise2

# Build rule for target.
BasicLightingExercise2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BasicLightingExercise2
.PHONY : BasicLightingExercise2

# fast build rule for target.
BasicLightingExercise2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BasicLightingExercise2.dir/build.make CMakeFiles/BasicLightingExercise2.dir/build
.PHONY : BasicLightingExercise2/fast

#=============================================================================
# Target rules for targets named BasicLightingExercise3

# Build rule for target.
BasicLightingExercise3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BasicLightingExercise3
.PHONY : BasicLightingExercise3

# fast build rule for target.
BasicLightingExercise3/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BasicLightingExercise3.dir/build.make CMakeFiles/BasicLightingExercise3.dir/build
.PHONY : BasicLightingExercise3/fast

#=============================================================================
# Target rules for targets named BasicLightingExercise4

# Build rule for target.
BasicLightingExercise4: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BasicLightingExercise4
.PHONY : BasicLightingExercise4

# fast build rule for target.
BasicLightingExercise4/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BasicLightingExercise4.dir/build.make CMakeFiles/BasicLightingExercise4.dir/build
.PHONY : BasicLightingExercise4/fast

#=============================================================================
# Target rules for targets named MaterialsMain

# Build rule for target.
MaterialsMain: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MaterialsMain
.PHONY : MaterialsMain

# fast build rule for target.
MaterialsMain/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MaterialsMain.dir/build.make CMakeFiles/MaterialsMain.dir/build
.PHONY : MaterialsMain/fast

#=============================================================================
# Target rules for targets named MaterialsExercise1

# Build rule for target.
MaterialsExercise1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MaterialsExercise1
.PHONY : MaterialsExercise1

# fast build rule for target.
MaterialsExercise1/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MaterialsExercise1.dir/build.make CMakeFiles/MaterialsExercise1.dir/build
.PHONY : MaterialsExercise1/fast

#=============================================================================
# Target rules for targets named MaterialsExercise2

# Build rule for target.
MaterialsExercise2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MaterialsExercise2
.PHONY : MaterialsExercise2

# fast build rule for target.
MaterialsExercise2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MaterialsExercise2.dir/build.make CMakeFiles/MaterialsExercise2.dir/build
.PHONY : MaterialsExercise2/fast

#=============================================================================
# Target rules for targets named LightingMapsMain

# Build rule for target.
LightingMapsMain: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LightingMapsMain
.PHONY : LightingMapsMain

# fast build rule for target.
LightingMapsMain/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LightingMapsMain.dir/build.make CMakeFiles/LightingMapsMain.dir/build
.PHONY : LightingMapsMain/fast

#=============================================================================
# Target rules for targets named LightingMapsExercise1

# Build rule for target.
LightingMapsExercise1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LightingMapsExercise1
.PHONY : LightingMapsExercise1

# fast build rule for target.
LightingMapsExercise1/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LightingMapsExercise1.dir/build.make CMakeFiles/LightingMapsExercise1.dir/build
.PHONY : LightingMapsExercise1/fast

#=============================================================================
# Target rules for targets named LightingMapsExercise2

# Build rule for target.
LightingMapsExercise2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LightingMapsExercise2
.PHONY : LightingMapsExercise2

# fast build rule for target.
LightingMapsExercise2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LightingMapsExercise2.dir/build.make CMakeFiles/LightingMapsExercise2.dir/build
.PHONY : LightingMapsExercise2/fast

#=============================================================================
# Target rules for targets named LightingMapsExercise3

# Build rule for target.
LightingMapsExercise3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LightingMapsExercise3
.PHONY : LightingMapsExercise3

# fast build rule for target.
LightingMapsExercise3/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LightingMapsExercise3.dir/build.make CMakeFiles/LightingMapsExercise3.dir/build
.PHONY : LightingMapsExercise3/fast

#=============================================================================
# Target rules for targets named MultipleLightsExercise1

# Build rule for target.
MultipleLightsExercise1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MultipleLightsExercise1
.PHONY : MultipleLightsExercise1

# fast build rule for target.
MultipleLightsExercise1/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MultipleLightsExercise1.dir/build.make CMakeFiles/MultipleLightsExercise1.dir/build
.PHONY : MultipleLightsExercise1/fast

src/basic_lighting_exercise1.o: src/basic_lighting_exercise1.cpp.o
.PHONY : src/basic_lighting_exercise1.o

# target to build an object file
src/basic_lighting_exercise1.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BasicLightingExercise1.dir/build.make CMakeFiles/BasicLightingExercise1.dir/src/basic_lighting_exercise1.cpp.o
.PHONY : src/basic_lighting_exercise1.cpp.o

src/basic_lighting_exercise1.i: src/basic_lighting_exercise1.cpp.i
.PHONY : src/basic_lighting_exercise1.i

# target to preprocess a source file
src/basic_lighting_exercise1.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BasicLightingExercise1.dir/build.make CMakeFiles/BasicLightingExercise1.dir/src/basic_lighting_exercise1.cpp.i
.PHONY : src/basic_lighting_exercise1.cpp.i

src/basic_lighting_exercise1.s: src/basic_lighting_exercise1.cpp.s
.PHONY : src/basic_lighting_exercise1.s

# target to generate assembly for a file
src/basic_lighting_exercise1.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BasicLightingExercise1.dir/build.make CMakeFiles/BasicLightingExercise1.dir/src/basic_lighting_exercise1.cpp.s
.PHONY : src/basic_lighting_exercise1.cpp.s

src/basic_lighting_exercise2.o: src/basic_lighting_exercise2.cpp.o
.PHONY : src/basic_lighting_exercise2.o

# target to build an object file
src/basic_lighting_exercise2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BasicLightingExercise2.dir/build.make CMakeFiles/BasicLightingExercise2.dir/src/basic_lighting_exercise2.cpp.o
.PHONY : src/basic_lighting_exercise2.cpp.o

src/basic_lighting_exercise2.i: src/basic_lighting_exercise2.cpp.i
.PHONY : src/basic_lighting_exercise2.i

# target to preprocess a source file
src/basic_lighting_exercise2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BasicLightingExercise2.dir/build.make CMakeFiles/BasicLightingExercise2.dir/src/basic_lighting_exercise2.cpp.i
.PHONY : src/basic_lighting_exercise2.cpp.i

src/basic_lighting_exercise2.s: src/basic_lighting_exercise2.cpp.s
.PHONY : src/basic_lighting_exercise2.s

# target to generate assembly for a file
src/basic_lighting_exercise2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BasicLightingExercise2.dir/build.make CMakeFiles/BasicLightingExercise2.dir/src/basic_lighting_exercise2.cpp.s
.PHONY : src/basic_lighting_exercise2.cpp.s

src/basic_lighting_exercise3.o: src/basic_lighting_exercise3.cpp.o
.PHONY : src/basic_lighting_exercise3.o

# target to build an object file
src/basic_lighting_exercise3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BasicLightingExercise3.dir/build.make CMakeFiles/BasicLightingExercise3.dir/src/basic_lighting_exercise3.cpp.o
.PHONY : src/basic_lighting_exercise3.cpp.o

src/basic_lighting_exercise3.i: src/basic_lighting_exercise3.cpp.i
.PHONY : src/basic_lighting_exercise3.i

# target to preprocess a source file
src/basic_lighting_exercise3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BasicLightingExercise3.dir/build.make CMakeFiles/BasicLightingExercise3.dir/src/basic_lighting_exercise3.cpp.i
.PHONY : src/basic_lighting_exercise3.cpp.i

src/basic_lighting_exercise3.s: src/basic_lighting_exercise3.cpp.s
.PHONY : src/basic_lighting_exercise3.s

# target to generate assembly for a file
src/basic_lighting_exercise3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BasicLightingExercise3.dir/build.make CMakeFiles/BasicLightingExercise3.dir/src/basic_lighting_exercise3.cpp.s
.PHONY : src/basic_lighting_exercise3.cpp.s

src/basic_lighting_exercise4.o: src/basic_lighting_exercise4.cpp.o
.PHONY : src/basic_lighting_exercise4.o

# target to build an object file
src/basic_lighting_exercise4.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BasicLightingExercise4.dir/build.make CMakeFiles/BasicLightingExercise4.dir/src/basic_lighting_exercise4.cpp.o
.PHONY : src/basic_lighting_exercise4.cpp.o

src/basic_lighting_exercise4.i: src/basic_lighting_exercise4.cpp.i
.PHONY : src/basic_lighting_exercise4.i

# target to preprocess a source file
src/basic_lighting_exercise4.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BasicLightingExercise4.dir/build.make CMakeFiles/BasicLightingExercise4.dir/src/basic_lighting_exercise4.cpp.i
.PHONY : src/basic_lighting_exercise4.cpp.i

src/basic_lighting_exercise4.s: src/basic_lighting_exercise4.cpp.s
.PHONY : src/basic_lighting_exercise4.s

# target to generate assembly for a file
src/basic_lighting_exercise4.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BasicLightingExercise4.dir/build.make CMakeFiles/BasicLightingExercise4.dir/src/basic_lighting_exercise4.cpp.s
.PHONY : src/basic_lighting_exercise4.cpp.s

src/basic_lighting_main.o: src/basic_lighting_main.cpp.o
.PHONY : src/basic_lighting_main.o

# target to build an object file
src/basic_lighting_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BasicLightingMain.dir/build.make CMakeFiles/BasicLightingMain.dir/src/basic_lighting_main.cpp.o
.PHONY : src/basic_lighting_main.cpp.o

src/basic_lighting_main.i: src/basic_lighting_main.cpp.i
.PHONY : src/basic_lighting_main.i

# target to preprocess a source file
src/basic_lighting_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BasicLightingMain.dir/build.make CMakeFiles/BasicLightingMain.dir/src/basic_lighting_main.cpp.i
.PHONY : src/basic_lighting_main.cpp.i

src/basic_lighting_main.s: src/basic_lighting_main.cpp.s
.PHONY : src/basic_lighting_main.s

# target to generate assembly for a file
src/basic_lighting_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BasicLightingMain.dir/build.make CMakeFiles/BasicLightingMain.dir/src/basic_lighting_main.cpp.s
.PHONY : src/basic_lighting_main.cpp.s

src/camera_exercise1.o: src/camera_exercise1.cpp.o
.PHONY : src/camera_exercise1.o

# target to build an object file
src/camera_exercise1.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CameraExercise1.dir/build.make CMakeFiles/CameraExercise1.dir/src/camera_exercise1.cpp.o
.PHONY : src/camera_exercise1.cpp.o

src/camera_exercise1.i: src/camera_exercise1.cpp.i
.PHONY : src/camera_exercise1.i

# target to preprocess a source file
src/camera_exercise1.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CameraExercise1.dir/build.make CMakeFiles/CameraExercise1.dir/src/camera_exercise1.cpp.i
.PHONY : src/camera_exercise1.cpp.i

src/camera_exercise1.s: src/camera_exercise1.cpp.s
.PHONY : src/camera_exercise1.s

# target to generate assembly for a file
src/camera_exercise1.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CameraExercise1.dir/build.make CMakeFiles/CameraExercise1.dir/src/camera_exercise1.cpp.s
.PHONY : src/camera_exercise1.cpp.s

src/camera_exercise2.o: src/camera_exercise2.cpp.o
.PHONY : src/camera_exercise2.o

# target to build an object file
src/camera_exercise2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CameraExercise2.dir/build.make CMakeFiles/CameraExercise2.dir/src/camera_exercise2.cpp.o
.PHONY : src/camera_exercise2.cpp.o

src/camera_exercise2.i: src/camera_exercise2.cpp.i
.PHONY : src/camera_exercise2.i

# target to preprocess a source file
src/camera_exercise2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CameraExercise2.dir/build.make CMakeFiles/CameraExercise2.dir/src/camera_exercise2.cpp.i
.PHONY : src/camera_exercise2.cpp.i

src/camera_exercise2.s: src/camera_exercise2.cpp.s
.PHONY : src/camera_exercise2.s

# target to generate assembly for a file
src/camera_exercise2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CameraExercise2.dir/build.make CMakeFiles/CameraExercise2.dir/src/camera_exercise2.cpp.s
.PHONY : src/camera_exercise2.cpp.s

src/camera_main.o: src/camera_main.cpp.o
.PHONY : src/camera_main.o

# target to build an object file
src/camera_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CameraMain.dir/build.make CMakeFiles/CameraMain.dir/src/camera_main.cpp.o
.PHONY : src/camera_main.cpp.o

src/camera_main.i: src/camera_main.cpp.i
.PHONY : src/camera_main.i

# target to preprocess a source file
src/camera_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CameraMain.dir/build.make CMakeFiles/CameraMain.dir/src/camera_main.cpp.i
.PHONY : src/camera_main.cpp.i

src/camera_main.s: src/camera_main.cpp.s
.PHONY : src/camera_main.s

# target to generate assembly for a file
src/camera_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CameraMain.dir/build.make CMakeFiles/CameraMain.dir/src/camera_main.cpp.s
.PHONY : src/camera_main.cpp.s

src/coordinate_systems_exercise1.o: src/coordinate_systems_exercise1.cpp.o
.PHONY : src/coordinate_systems_exercise1.o

# target to build an object file
src/coordinate_systems_exercise1.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoordinateSystemsExercise1.dir/build.make CMakeFiles/CoordinateSystemsExercise1.dir/src/coordinate_systems_exercise1.cpp.o
.PHONY : src/coordinate_systems_exercise1.cpp.o

src/coordinate_systems_exercise1.i: src/coordinate_systems_exercise1.cpp.i
.PHONY : src/coordinate_systems_exercise1.i

# target to preprocess a source file
src/coordinate_systems_exercise1.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoordinateSystemsExercise1.dir/build.make CMakeFiles/CoordinateSystemsExercise1.dir/src/coordinate_systems_exercise1.cpp.i
.PHONY : src/coordinate_systems_exercise1.cpp.i

src/coordinate_systems_exercise1.s: src/coordinate_systems_exercise1.cpp.s
.PHONY : src/coordinate_systems_exercise1.s

# target to generate assembly for a file
src/coordinate_systems_exercise1.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoordinateSystemsExercise1.dir/build.make CMakeFiles/CoordinateSystemsExercise1.dir/src/coordinate_systems_exercise1.cpp.s
.PHONY : src/coordinate_systems_exercise1.cpp.s

src/coordinate_systems_exercise2.o: src/coordinate_systems_exercise2.cpp.o
.PHONY : src/coordinate_systems_exercise2.o

# target to build an object file
src/coordinate_systems_exercise2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoordinateSystemsExercise2.dir/build.make CMakeFiles/CoordinateSystemsExercise2.dir/src/coordinate_systems_exercise2.cpp.o
.PHONY : src/coordinate_systems_exercise2.cpp.o

src/coordinate_systems_exercise2.i: src/coordinate_systems_exercise2.cpp.i
.PHONY : src/coordinate_systems_exercise2.i

# target to preprocess a source file
src/coordinate_systems_exercise2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoordinateSystemsExercise2.dir/build.make CMakeFiles/CoordinateSystemsExercise2.dir/src/coordinate_systems_exercise2.cpp.i
.PHONY : src/coordinate_systems_exercise2.cpp.i

src/coordinate_systems_exercise2.s: src/coordinate_systems_exercise2.cpp.s
.PHONY : src/coordinate_systems_exercise2.s

# target to generate assembly for a file
src/coordinate_systems_exercise2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoordinateSystemsExercise2.dir/build.make CMakeFiles/CoordinateSystemsExercise2.dir/src/coordinate_systems_exercise2.cpp.s
.PHONY : src/coordinate_systems_exercise2.cpp.s

src/coordinate_systems_exercise3.o: src/coordinate_systems_exercise3.cpp.o
.PHONY : src/coordinate_systems_exercise3.o

# target to build an object file
src/coordinate_systems_exercise3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoordinateSystemsExercise3.dir/build.make CMakeFiles/CoordinateSystemsExercise3.dir/src/coordinate_systems_exercise3.cpp.o
.PHONY : src/coordinate_systems_exercise3.cpp.o

src/coordinate_systems_exercise3.i: src/coordinate_systems_exercise3.cpp.i
.PHONY : src/coordinate_systems_exercise3.i

# target to preprocess a source file
src/coordinate_systems_exercise3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoordinateSystemsExercise3.dir/build.make CMakeFiles/CoordinateSystemsExercise3.dir/src/coordinate_systems_exercise3.cpp.i
.PHONY : src/coordinate_systems_exercise3.cpp.i

src/coordinate_systems_exercise3.s: src/coordinate_systems_exercise3.cpp.s
.PHONY : src/coordinate_systems_exercise3.s

# target to generate assembly for a file
src/coordinate_systems_exercise3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoordinateSystemsExercise3.dir/build.make CMakeFiles/CoordinateSystemsExercise3.dir/src/coordinate_systems_exercise3.cpp.s
.PHONY : src/coordinate_systems_exercise3.cpp.s

src/coordinate_systems_main.o: src/coordinate_systems_main.cpp.o
.PHONY : src/coordinate_systems_main.o

# target to build an object file
src/coordinate_systems_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoordinateSystemsMain.dir/build.make CMakeFiles/CoordinateSystemsMain.dir/src/coordinate_systems_main.cpp.o
.PHONY : src/coordinate_systems_main.cpp.o

src/coordinate_systems_main.i: src/coordinate_systems_main.cpp.i
.PHONY : src/coordinate_systems_main.i

# target to preprocess a source file
src/coordinate_systems_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoordinateSystemsMain.dir/build.make CMakeFiles/CoordinateSystemsMain.dir/src/coordinate_systems_main.cpp.i
.PHONY : src/coordinate_systems_main.cpp.i

src/coordinate_systems_main.s: src/coordinate_systems_main.cpp.s
.PHONY : src/coordinate_systems_main.s

# target to generate assembly for a file
src/coordinate_systems_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoordinateSystemsMain.dir/build.make CMakeFiles/CoordinateSystemsMain.dir/src/coordinate_systems_main.cpp.s
.PHONY : src/coordinate_systems_main.cpp.s

src/exercise1.o: src/exercise1.cpp.o
.PHONY : src/exercise1.o

# target to build an object file
src/exercise1.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Exercise1.dir/build.make CMakeFiles/Exercise1.dir/src/exercise1.cpp.o
.PHONY : src/exercise1.cpp.o

src/exercise1.i: src/exercise1.cpp.i
.PHONY : src/exercise1.i

# target to preprocess a source file
src/exercise1.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Exercise1.dir/build.make CMakeFiles/Exercise1.dir/src/exercise1.cpp.i
.PHONY : src/exercise1.cpp.i

src/exercise1.s: src/exercise1.cpp.s
.PHONY : src/exercise1.s

# target to generate assembly for a file
src/exercise1.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Exercise1.dir/build.make CMakeFiles/Exercise1.dir/src/exercise1.cpp.s
.PHONY : src/exercise1.cpp.s

src/exercise2.o: src/exercise2.cpp.o
.PHONY : src/exercise2.o

# target to build an object file
src/exercise2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Exercise2.dir/build.make CMakeFiles/Exercise2.dir/src/exercise2.cpp.o
.PHONY : src/exercise2.cpp.o

src/exercise2.i: src/exercise2.cpp.i
.PHONY : src/exercise2.i

# target to preprocess a source file
src/exercise2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Exercise2.dir/build.make CMakeFiles/Exercise2.dir/src/exercise2.cpp.i
.PHONY : src/exercise2.cpp.i

src/exercise2.s: src/exercise2.cpp.s
.PHONY : src/exercise2.s

# target to generate assembly for a file
src/exercise2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Exercise2.dir/build.make CMakeFiles/Exercise2.dir/src/exercise2.cpp.s
.PHONY : src/exercise2.cpp.s

src/exercise3.o: src/exercise3.cpp.o
.PHONY : src/exercise3.o

# target to build an object file
src/exercise3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Exercise3.dir/build.make CMakeFiles/Exercise3.dir/src/exercise3.cpp.o
.PHONY : src/exercise3.cpp.o

src/exercise3.i: src/exercise3.cpp.i
.PHONY : src/exercise3.i

# target to preprocess a source file
src/exercise3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Exercise3.dir/build.make CMakeFiles/Exercise3.dir/src/exercise3.cpp.i
.PHONY : src/exercise3.cpp.i

src/exercise3.s: src/exercise3.cpp.s
.PHONY : src/exercise3.s

# target to generate assembly for a file
src/exercise3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Exercise3.dir/build.make CMakeFiles/Exercise3.dir/src/exercise3.cpp.s
.PHONY : src/exercise3.cpp.s

src/glad.o: src/glad.c.o
.PHONY : src/glad.o

# target to build an object file
src/glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenGLSetup.dir/build.make CMakeFiles/OpenGLSetup.dir/src/glad.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Exercise1.dir/build.make CMakeFiles/Exercise1.dir/src/glad.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Exercise2.dir/build.make CMakeFiles/Exercise2.dir/src/glad.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Exercise3.dir/build.make CMakeFiles/Exercise3.dir/src/glad.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ShaderExercise1.dir/build.make CMakeFiles/ShaderExercise1.dir/src/glad.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ShaderExercise2.dir/build.make CMakeFiles/ShaderExercise2.dir/src/glad.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ShaderExercise3.dir/build.make CMakeFiles/ShaderExercise3.dir/src/glad.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TransformMain.dir/build.make CMakeFiles/TransformMain.dir/src/glad.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TransformExercise1.dir/build.make CMakeFiles/TransformExercise1.dir/src/glad.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TransformExercise2.dir/build.make CMakeFiles/TransformExercise2.dir/src/glad.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextureMain.dir/build.make CMakeFiles/TextureMain.dir/src/glad.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextureExercise1.dir/build.make CMakeFiles/TextureExercise1.dir/src/glad.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextureExercise2.dir/build.make CMakeFiles/TextureExercise2.dir/src/glad.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextureExercise3.dir/build.make CMakeFiles/TextureExercise3.dir/src/glad.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextureExercise4.dir/build.make CMakeFiles/TextureExercise4.dir/src/glad.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoordinateSystemsMain.dir/build.make CMakeFiles/CoordinateSystemsMain.dir/src/glad.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoordinateSystemsExercise1.dir/build.make CMakeFiles/CoordinateSystemsExercise1.dir/src/glad.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoordinateSystemsExercise2.dir/build.make CMakeFiles/CoordinateSystemsExercise2.dir/src/glad.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoordinateSystemsExercise3.dir/build.make CMakeFiles/CoordinateSystemsExercise3.dir/src/glad.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CameraMain.dir/build.make CMakeFiles/CameraMain.dir/src/glad.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CameraExercise1.dir/build.make CMakeFiles/CameraExercise1.dir/src/glad.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CameraExercise2.dir/build.make CMakeFiles/CameraExercise2.dir/src/glad.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TugasPersegi.dir/build.make CMakeFiles/TugasPersegi.dir/src/glad.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BasicLightingMain.dir/build.make CMakeFiles/BasicLightingMain.dir/src/glad.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BasicLightingExercise1.dir/build.make CMakeFiles/BasicLightingExercise1.dir/src/glad.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BasicLightingExercise2.dir/build.make CMakeFiles/BasicLightingExercise2.dir/src/glad.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BasicLightingExercise3.dir/build.make CMakeFiles/BasicLightingExercise3.dir/src/glad.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BasicLightingExercise4.dir/build.make CMakeFiles/BasicLightingExercise4.dir/src/glad.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MaterialsMain.dir/build.make CMakeFiles/MaterialsMain.dir/src/glad.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MaterialsExercise1.dir/build.make CMakeFiles/MaterialsExercise1.dir/src/glad.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MaterialsExercise2.dir/build.make CMakeFiles/MaterialsExercise2.dir/src/glad.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LightingMapsMain.dir/build.make CMakeFiles/LightingMapsMain.dir/src/glad.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LightingMapsExercise1.dir/build.make CMakeFiles/LightingMapsExercise1.dir/src/glad.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LightingMapsExercise2.dir/build.make CMakeFiles/LightingMapsExercise2.dir/src/glad.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LightingMapsExercise3.dir/build.make CMakeFiles/LightingMapsExercise3.dir/src/glad.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MultipleLightsExercise1.dir/build.make CMakeFiles/MultipleLightsExercise1.dir/src/glad.c.o
.PHONY : src/glad.c.o

src/glad.i: src/glad.c.i
.PHONY : src/glad.i

# target to preprocess a source file
src/glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenGLSetup.dir/build.make CMakeFiles/OpenGLSetup.dir/src/glad.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Exercise1.dir/build.make CMakeFiles/Exercise1.dir/src/glad.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Exercise2.dir/build.make CMakeFiles/Exercise2.dir/src/glad.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Exercise3.dir/build.make CMakeFiles/Exercise3.dir/src/glad.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ShaderExercise1.dir/build.make CMakeFiles/ShaderExercise1.dir/src/glad.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ShaderExercise2.dir/build.make CMakeFiles/ShaderExercise2.dir/src/glad.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ShaderExercise3.dir/build.make CMakeFiles/ShaderExercise3.dir/src/glad.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TransformMain.dir/build.make CMakeFiles/TransformMain.dir/src/glad.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TransformExercise1.dir/build.make CMakeFiles/TransformExercise1.dir/src/glad.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TransformExercise2.dir/build.make CMakeFiles/TransformExercise2.dir/src/glad.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextureMain.dir/build.make CMakeFiles/TextureMain.dir/src/glad.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextureExercise1.dir/build.make CMakeFiles/TextureExercise1.dir/src/glad.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextureExercise2.dir/build.make CMakeFiles/TextureExercise2.dir/src/glad.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextureExercise3.dir/build.make CMakeFiles/TextureExercise3.dir/src/glad.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextureExercise4.dir/build.make CMakeFiles/TextureExercise4.dir/src/glad.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoordinateSystemsMain.dir/build.make CMakeFiles/CoordinateSystemsMain.dir/src/glad.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoordinateSystemsExercise1.dir/build.make CMakeFiles/CoordinateSystemsExercise1.dir/src/glad.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoordinateSystemsExercise2.dir/build.make CMakeFiles/CoordinateSystemsExercise2.dir/src/glad.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoordinateSystemsExercise3.dir/build.make CMakeFiles/CoordinateSystemsExercise3.dir/src/glad.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CameraMain.dir/build.make CMakeFiles/CameraMain.dir/src/glad.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CameraExercise1.dir/build.make CMakeFiles/CameraExercise1.dir/src/glad.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CameraExercise2.dir/build.make CMakeFiles/CameraExercise2.dir/src/glad.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TugasPersegi.dir/build.make CMakeFiles/TugasPersegi.dir/src/glad.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BasicLightingMain.dir/build.make CMakeFiles/BasicLightingMain.dir/src/glad.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BasicLightingExercise1.dir/build.make CMakeFiles/BasicLightingExercise1.dir/src/glad.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BasicLightingExercise2.dir/build.make CMakeFiles/BasicLightingExercise2.dir/src/glad.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BasicLightingExercise3.dir/build.make CMakeFiles/BasicLightingExercise3.dir/src/glad.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BasicLightingExercise4.dir/build.make CMakeFiles/BasicLightingExercise4.dir/src/glad.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MaterialsMain.dir/build.make CMakeFiles/MaterialsMain.dir/src/glad.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MaterialsExercise1.dir/build.make CMakeFiles/MaterialsExercise1.dir/src/glad.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MaterialsExercise2.dir/build.make CMakeFiles/MaterialsExercise2.dir/src/glad.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LightingMapsMain.dir/build.make CMakeFiles/LightingMapsMain.dir/src/glad.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LightingMapsExercise1.dir/build.make CMakeFiles/LightingMapsExercise1.dir/src/glad.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LightingMapsExercise2.dir/build.make CMakeFiles/LightingMapsExercise2.dir/src/glad.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LightingMapsExercise3.dir/build.make CMakeFiles/LightingMapsExercise3.dir/src/glad.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MultipleLightsExercise1.dir/build.make CMakeFiles/MultipleLightsExercise1.dir/src/glad.c.i
.PHONY : src/glad.c.i

src/glad.s: src/glad.c.s
.PHONY : src/glad.s

# target to generate assembly for a file
src/glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenGLSetup.dir/build.make CMakeFiles/OpenGLSetup.dir/src/glad.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Exercise1.dir/build.make CMakeFiles/Exercise1.dir/src/glad.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Exercise2.dir/build.make CMakeFiles/Exercise2.dir/src/glad.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Exercise3.dir/build.make CMakeFiles/Exercise3.dir/src/glad.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ShaderExercise1.dir/build.make CMakeFiles/ShaderExercise1.dir/src/glad.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ShaderExercise2.dir/build.make CMakeFiles/ShaderExercise2.dir/src/glad.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ShaderExercise3.dir/build.make CMakeFiles/ShaderExercise3.dir/src/glad.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TransformMain.dir/build.make CMakeFiles/TransformMain.dir/src/glad.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TransformExercise1.dir/build.make CMakeFiles/TransformExercise1.dir/src/glad.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TransformExercise2.dir/build.make CMakeFiles/TransformExercise2.dir/src/glad.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextureMain.dir/build.make CMakeFiles/TextureMain.dir/src/glad.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextureExercise1.dir/build.make CMakeFiles/TextureExercise1.dir/src/glad.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextureExercise2.dir/build.make CMakeFiles/TextureExercise2.dir/src/glad.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextureExercise3.dir/build.make CMakeFiles/TextureExercise3.dir/src/glad.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextureExercise4.dir/build.make CMakeFiles/TextureExercise4.dir/src/glad.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoordinateSystemsMain.dir/build.make CMakeFiles/CoordinateSystemsMain.dir/src/glad.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoordinateSystemsExercise1.dir/build.make CMakeFiles/CoordinateSystemsExercise1.dir/src/glad.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoordinateSystemsExercise2.dir/build.make CMakeFiles/CoordinateSystemsExercise2.dir/src/glad.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CoordinateSystemsExercise3.dir/build.make CMakeFiles/CoordinateSystemsExercise3.dir/src/glad.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CameraMain.dir/build.make CMakeFiles/CameraMain.dir/src/glad.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CameraExercise1.dir/build.make CMakeFiles/CameraExercise1.dir/src/glad.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CameraExercise2.dir/build.make CMakeFiles/CameraExercise2.dir/src/glad.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TugasPersegi.dir/build.make CMakeFiles/TugasPersegi.dir/src/glad.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BasicLightingMain.dir/build.make CMakeFiles/BasicLightingMain.dir/src/glad.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BasicLightingExercise1.dir/build.make CMakeFiles/BasicLightingExercise1.dir/src/glad.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BasicLightingExercise2.dir/build.make CMakeFiles/BasicLightingExercise2.dir/src/glad.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BasicLightingExercise3.dir/build.make CMakeFiles/BasicLightingExercise3.dir/src/glad.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BasicLightingExercise4.dir/build.make CMakeFiles/BasicLightingExercise4.dir/src/glad.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MaterialsMain.dir/build.make CMakeFiles/MaterialsMain.dir/src/glad.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MaterialsExercise1.dir/build.make CMakeFiles/MaterialsExercise1.dir/src/glad.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MaterialsExercise2.dir/build.make CMakeFiles/MaterialsExercise2.dir/src/glad.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LightingMapsMain.dir/build.make CMakeFiles/LightingMapsMain.dir/src/glad.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LightingMapsExercise1.dir/build.make CMakeFiles/LightingMapsExercise1.dir/src/glad.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LightingMapsExercise2.dir/build.make CMakeFiles/LightingMapsExercise2.dir/src/glad.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LightingMapsExercise3.dir/build.make CMakeFiles/LightingMapsExercise3.dir/src/glad.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MultipleLightsExercise1.dir/build.make CMakeFiles/MultipleLightsExercise1.dir/src/glad.c.s
.PHONY : src/glad.c.s

src/lighting_maps_exercise1.o: src/lighting_maps_exercise1.cpp.o
.PHONY : src/lighting_maps_exercise1.o

# target to build an object file
src/lighting_maps_exercise1.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LightingMapsExercise1.dir/build.make CMakeFiles/LightingMapsExercise1.dir/src/lighting_maps_exercise1.cpp.o
.PHONY : src/lighting_maps_exercise1.cpp.o

src/lighting_maps_exercise1.i: src/lighting_maps_exercise1.cpp.i
.PHONY : src/lighting_maps_exercise1.i

# target to preprocess a source file
src/lighting_maps_exercise1.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LightingMapsExercise1.dir/build.make CMakeFiles/LightingMapsExercise1.dir/src/lighting_maps_exercise1.cpp.i
.PHONY : src/lighting_maps_exercise1.cpp.i

src/lighting_maps_exercise1.s: src/lighting_maps_exercise1.cpp.s
.PHONY : src/lighting_maps_exercise1.s

# target to generate assembly for a file
src/lighting_maps_exercise1.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LightingMapsExercise1.dir/build.make CMakeFiles/LightingMapsExercise1.dir/src/lighting_maps_exercise1.cpp.s
.PHONY : src/lighting_maps_exercise1.cpp.s

src/lighting_maps_exercise2.o: src/lighting_maps_exercise2.cpp.o
.PHONY : src/lighting_maps_exercise2.o

# target to build an object file
src/lighting_maps_exercise2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LightingMapsExercise2.dir/build.make CMakeFiles/LightingMapsExercise2.dir/src/lighting_maps_exercise2.cpp.o
.PHONY : src/lighting_maps_exercise2.cpp.o

src/lighting_maps_exercise2.i: src/lighting_maps_exercise2.cpp.i
.PHONY : src/lighting_maps_exercise2.i

# target to preprocess a source file
src/lighting_maps_exercise2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LightingMapsExercise2.dir/build.make CMakeFiles/LightingMapsExercise2.dir/src/lighting_maps_exercise2.cpp.i
.PHONY : src/lighting_maps_exercise2.cpp.i

src/lighting_maps_exercise2.s: src/lighting_maps_exercise2.cpp.s
.PHONY : src/lighting_maps_exercise2.s

# target to generate assembly for a file
src/lighting_maps_exercise2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LightingMapsExercise2.dir/build.make CMakeFiles/LightingMapsExercise2.dir/src/lighting_maps_exercise2.cpp.s
.PHONY : src/lighting_maps_exercise2.cpp.s

src/lighting_maps_exercise3.o: src/lighting_maps_exercise3.cpp.o
.PHONY : src/lighting_maps_exercise3.o

# target to build an object file
src/lighting_maps_exercise3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LightingMapsExercise3.dir/build.make CMakeFiles/LightingMapsExercise3.dir/src/lighting_maps_exercise3.cpp.o
.PHONY : src/lighting_maps_exercise3.cpp.o

src/lighting_maps_exercise3.i: src/lighting_maps_exercise3.cpp.i
.PHONY : src/lighting_maps_exercise3.i

# target to preprocess a source file
src/lighting_maps_exercise3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LightingMapsExercise3.dir/build.make CMakeFiles/LightingMapsExercise3.dir/src/lighting_maps_exercise3.cpp.i
.PHONY : src/lighting_maps_exercise3.cpp.i

src/lighting_maps_exercise3.s: src/lighting_maps_exercise3.cpp.s
.PHONY : src/lighting_maps_exercise3.s

# target to generate assembly for a file
src/lighting_maps_exercise3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LightingMapsExercise3.dir/build.make CMakeFiles/LightingMapsExercise3.dir/src/lighting_maps_exercise3.cpp.s
.PHONY : src/lighting_maps_exercise3.cpp.s

src/lighting_maps_main.o: src/lighting_maps_main.cpp.o
.PHONY : src/lighting_maps_main.o

# target to build an object file
src/lighting_maps_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LightingMapsMain.dir/build.make CMakeFiles/LightingMapsMain.dir/src/lighting_maps_main.cpp.o
.PHONY : src/lighting_maps_main.cpp.o

src/lighting_maps_main.i: src/lighting_maps_main.cpp.i
.PHONY : src/lighting_maps_main.i

# target to preprocess a source file
src/lighting_maps_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LightingMapsMain.dir/build.make CMakeFiles/LightingMapsMain.dir/src/lighting_maps_main.cpp.i
.PHONY : src/lighting_maps_main.cpp.i

src/lighting_maps_main.s: src/lighting_maps_main.cpp.s
.PHONY : src/lighting_maps_main.s

# target to generate assembly for a file
src/lighting_maps_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LightingMapsMain.dir/build.make CMakeFiles/LightingMapsMain.dir/src/lighting_maps_main.cpp.s
.PHONY : src/lighting_maps_main.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenGLSetup.dir/build.make CMakeFiles/OpenGLSetup.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenGLSetup.dir/build.make CMakeFiles/OpenGLSetup.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenGLSetup.dir/build.make CMakeFiles/OpenGLSetup.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/materials_exercise1.o: src/materials_exercise1.cpp.o
.PHONY : src/materials_exercise1.o

# target to build an object file
src/materials_exercise1.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MaterialsExercise1.dir/build.make CMakeFiles/MaterialsExercise1.dir/src/materials_exercise1.cpp.o
.PHONY : src/materials_exercise1.cpp.o

src/materials_exercise1.i: src/materials_exercise1.cpp.i
.PHONY : src/materials_exercise1.i

# target to preprocess a source file
src/materials_exercise1.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MaterialsExercise1.dir/build.make CMakeFiles/MaterialsExercise1.dir/src/materials_exercise1.cpp.i
.PHONY : src/materials_exercise1.cpp.i

src/materials_exercise1.s: src/materials_exercise1.cpp.s
.PHONY : src/materials_exercise1.s

# target to generate assembly for a file
src/materials_exercise1.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MaterialsExercise1.dir/build.make CMakeFiles/MaterialsExercise1.dir/src/materials_exercise1.cpp.s
.PHONY : src/materials_exercise1.cpp.s

src/materials_exercise2.o: src/materials_exercise2.cpp.o
.PHONY : src/materials_exercise2.o

# target to build an object file
src/materials_exercise2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MaterialsExercise2.dir/build.make CMakeFiles/MaterialsExercise2.dir/src/materials_exercise2.cpp.o
.PHONY : src/materials_exercise2.cpp.o

src/materials_exercise2.i: src/materials_exercise2.cpp.i
.PHONY : src/materials_exercise2.i

# target to preprocess a source file
src/materials_exercise2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MaterialsExercise2.dir/build.make CMakeFiles/MaterialsExercise2.dir/src/materials_exercise2.cpp.i
.PHONY : src/materials_exercise2.cpp.i

src/materials_exercise2.s: src/materials_exercise2.cpp.s
.PHONY : src/materials_exercise2.s

# target to generate assembly for a file
src/materials_exercise2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MaterialsExercise2.dir/build.make CMakeFiles/MaterialsExercise2.dir/src/materials_exercise2.cpp.s
.PHONY : src/materials_exercise2.cpp.s

src/materials_main.o: src/materials_main.cpp.o
.PHONY : src/materials_main.o

# target to build an object file
src/materials_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MaterialsMain.dir/build.make CMakeFiles/MaterialsMain.dir/src/materials_main.cpp.o
.PHONY : src/materials_main.cpp.o

src/materials_main.i: src/materials_main.cpp.i
.PHONY : src/materials_main.i

# target to preprocess a source file
src/materials_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MaterialsMain.dir/build.make CMakeFiles/MaterialsMain.dir/src/materials_main.cpp.i
.PHONY : src/materials_main.cpp.i

src/materials_main.s: src/materials_main.cpp.s
.PHONY : src/materials_main.s

# target to generate assembly for a file
src/materials_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MaterialsMain.dir/build.make CMakeFiles/MaterialsMain.dir/src/materials_main.cpp.s
.PHONY : src/materials_main.cpp.s

src/multiple_lights_exercise1.o: src/multiple_lights_exercise1.cpp.o
.PHONY : src/multiple_lights_exercise1.o

# target to build an object file
src/multiple_lights_exercise1.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MultipleLightsExercise1.dir/build.make CMakeFiles/MultipleLightsExercise1.dir/src/multiple_lights_exercise1.cpp.o
.PHONY : src/multiple_lights_exercise1.cpp.o

src/multiple_lights_exercise1.i: src/multiple_lights_exercise1.cpp.i
.PHONY : src/multiple_lights_exercise1.i

# target to preprocess a source file
src/multiple_lights_exercise1.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MultipleLightsExercise1.dir/build.make CMakeFiles/MultipleLightsExercise1.dir/src/multiple_lights_exercise1.cpp.i
.PHONY : src/multiple_lights_exercise1.cpp.i

src/multiple_lights_exercise1.s: src/multiple_lights_exercise1.cpp.s
.PHONY : src/multiple_lights_exercise1.s

# target to generate assembly for a file
src/multiple_lights_exercise1.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MultipleLightsExercise1.dir/build.make CMakeFiles/MultipleLightsExercise1.dir/src/multiple_lights_exercise1.cpp.s
.PHONY : src/multiple_lights_exercise1.cpp.s

src/shader_exercise1.o: src/shader_exercise1.cpp.o
.PHONY : src/shader_exercise1.o

# target to build an object file
src/shader_exercise1.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ShaderExercise1.dir/build.make CMakeFiles/ShaderExercise1.dir/src/shader_exercise1.cpp.o
.PHONY : src/shader_exercise1.cpp.o

src/shader_exercise1.i: src/shader_exercise1.cpp.i
.PHONY : src/shader_exercise1.i

# target to preprocess a source file
src/shader_exercise1.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ShaderExercise1.dir/build.make CMakeFiles/ShaderExercise1.dir/src/shader_exercise1.cpp.i
.PHONY : src/shader_exercise1.cpp.i

src/shader_exercise1.s: src/shader_exercise1.cpp.s
.PHONY : src/shader_exercise1.s

# target to generate assembly for a file
src/shader_exercise1.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ShaderExercise1.dir/build.make CMakeFiles/ShaderExercise1.dir/src/shader_exercise1.cpp.s
.PHONY : src/shader_exercise1.cpp.s

src/shader_exercise2.o: src/shader_exercise2.cpp.o
.PHONY : src/shader_exercise2.o

# target to build an object file
src/shader_exercise2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ShaderExercise2.dir/build.make CMakeFiles/ShaderExercise2.dir/src/shader_exercise2.cpp.o
.PHONY : src/shader_exercise2.cpp.o

src/shader_exercise2.i: src/shader_exercise2.cpp.i
.PHONY : src/shader_exercise2.i

# target to preprocess a source file
src/shader_exercise2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ShaderExercise2.dir/build.make CMakeFiles/ShaderExercise2.dir/src/shader_exercise2.cpp.i
.PHONY : src/shader_exercise2.cpp.i

src/shader_exercise2.s: src/shader_exercise2.cpp.s
.PHONY : src/shader_exercise2.s

# target to generate assembly for a file
src/shader_exercise2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ShaderExercise2.dir/build.make CMakeFiles/ShaderExercise2.dir/src/shader_exercise2.cpp.s
.PHONY : src/shader_exercise2.cpp.s

src/shader_exercise3.o: src/shader_exercise3.cpp.o
.PHONY : src/shader_exercise3.o

# target to build an object file
src/shader_exercise3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ShaderExercise3.dir/build.make CMakeFiles/ShaderExercise3.dir/src/shader_exercise3.cpp.o
.PHONY : src/shader_exercise3.cpp.o

src/shader_exercise3.i: src/shader_exercise3.cpp.i
.PHONY : src/shader_exercise3.i

# target to preprocess a source file
src/shader_exercise3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ShaderExercise3.dir/build.make CMakeFiles/ShaderExercise3.dir/src/shader_exercise3.cpp.i
.PHONY : src/shader_exercise3.cpp.i

src/shader_exercise3.s: src/shader_exercise3.cpp.s
.PHONY : src/shader_exercise3.s

# target to generate assembly for a file
src/shader_exercise3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ShaderExercise3.dir/build.make CMakeFiles/ShaderExercise3.dir/src/shader_exercise3.cpp.s
.PHONY : src/shader_exercise3.cpp.s

src/texture_exercise1.o: src/texture_exercise1.cpp.o
.PHONY : src/texture_exercise1.o

# target to build an object file
src/texture_exercise1.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextureExercise1.dir/build.make CMakeFiles/TextureExercise1.dir/src/texture_exercise1.cpp.o
.PHONY : src/texture_exercise1.cpp.o

src/texture_exercise1.i: src/texture_exercise1.cpp.i
.PHONY : src/texture_exercise1.i

# target to preprocess a source file
src/texture_exercise1.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextureExercise1.dir/build.make CMakeFiles/TextureExercise1.dir/src/texture_exercise1.cpp.i
.PHONY : src/texture_exercise1.cpp.i

src/texture_exercise1.s: src/texture_exercise1.cpp.s
.PHONY : src/texture_exercise1.s

# target to generate assembly for a file
src/texture_exercise1.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextureExercise1.dir/build.make CMakeFiles/TextureExercise1.dir/src/texture_exercise1.cpp.s
.PHONY : src/texture_exercise1.cpp.s

src/texture_exercise2.o: src/texture_exercise2.cpp.o
.PHONY : src/texture_exercise2.o

# target to build an object file
src/texture_exercise2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextureExercise2.dir/build.make CMakeFiles/TextureExercise2.dir/src/texture_exercise2.cpp.o
.PHONY : src/texture_exercise2.cpp.o

src/texture_exercise2.i: src/texture_exercise2.cpp.i
.PHONY : src/texture_exercise2.i

# target to preprocess a source file
src/texture_exercise2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextureExercise2.dir/build.make CMakeFiles/TextureExercise2.dir/src/texture_exercise2.cpp.i
.PHONY : src/texture_exercise2.cpp.i

src/texture_exercise2.s: src/texture_exercise2.cpp.s
.PHONY : src/texture_exercise2.s

# target to generate assembly for a file
src/texture_exercise2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextureExercise2.dir/build.make CMakeFiles/TextureExercise2.dir/src/texture_exercise2.cpp.s
.PHONY : src/texture_exercise2.cpp.s

src/texture_exercise3.o: src/texture_exercise3.cpp.o
.PHONY : src/texture_exercise3.o

# target to build an object file
src/texture_exercise3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextureExercise3.dir/build.make CMakeFiles/TextureExercise3.dir/src/texture_exercise3.cpp.o
.PHONY : src/texture_exercise3.cpp.o

src/texture_exercise3.i: src/texture_exercise3.cpp.i
.PHONY : src/texture_exercise3.i

# target to preprocess a source file
src/texture_exercise3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextureExercise3.dir/build.make CMakeFiles/TextureExercise3.dir/src/texture_exercise3.cpp.i
.PHONY : src/texture_exercise3.cpp.i

src/texture_exercise3.s: src/texture_exercise3.cpp.s
.PHONY : src/texture_exercise3.s

# target to generate assembly for a file
src/texture_exercise3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextureExercise3.dir/build.make CMakeFiles/TextureExercise3.dir/src/texture_exercise3.cpp.s
.PHONY : src/texture_exercise3.cpp.s

src/texture_exercise4.o: src/texture_exercise4.cpp.o
.PHONY : src/texture_exercise4.o

# target to build an object file
src/texture_exercise4.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextureExercise4.dir/build.make CMakeFiles/TextureExercise4.dir/src/texture_exercise4.cpp.o
.PHONY : src/texture_exercise4.cpp.o

src/texture_exercise4.i: src/texture_exercise4.cpp.i
.PHONY : src/texture_exercise4.i

# target to preprocess a source file
src/texture_exercise4.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextureExercise4.dir/build.make CMakeFiles/TextureExercise4.dir/src/texture_exercise4.cpp.i
.PHONY : src/texture_exercise4.cpp.i

src/texture_exercise4.s: src/texture_exercise4.cpp.s
.PHONY : src/texture_exercise4.s

# target to generate assembly for a file
src/texture_exercise4.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextureExercise4.dir/build.make CMakeFiles/TextureExercise4.dir/src/texture_exercise4.cpp.s
.PHONY : src/texture_exercise4.cpp.s

src/texture_main.o: src/texture_main.cpp.o
.PHONY : src/texture_main.o

# target to build an object file
src/texture_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextureMain.dir/build.make CMakeFiles/TextureMain.dir/src/texture_main.cpp.o
.PHONY : src/texture_main.cpp.o

src/texture_main.i: src/texture_main.cpp.i
.PHONY : src/texture_main.i

# target to preprocess a source file
src/texture_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextureMain.dir/build.make CMakeFiles/TextureMain.dir/src/texture_main.cpp.i
.PHONY : src/texture_main.cpp.i

src/texture_main.s: src/texture_main.cpp.s
.PHONY : src/texture_main.s

# target to generate assembly for a file
src/texture_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextureMain.dir/build.make CMakeFiles/TextureMain.dir/src/texture_main.cpp.s
.PHONY : src/texture_main.cpp.s

src/transform_exercise1.o: src/transform_exercise1.cpp.o
.PHONY : src/transform_exercise1.o

# target to build an object file
src/transform_exercise1.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TransformExercise1.dir/build.make CMakeFiles/TransformExercise1.dir/src/transform_exercise1.cpp.o
.PHONY : src/transform_exercise1.cpp.o

src/transform_exercise1.i: src/transform_exercise1.cpp.i
.PHONY : src/transform_exercise1.i

# target to preprocess a source file
src/transform_exercise1.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TransformExercise1.dir/build.make CMakeFiles/TransformExercise1.dir/src/transform_exercise1.cpp.i
.PHONY : src/transform_exercise1.cpp.i

src/transform_exercise1.s: src/transform_exercise1.cpp.s
.PHONY : src/transform_exercise1.s

# target to generate assembly for a file
src/transform_exercise1.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TransformExercise1.dir/build.make CMakeFiles/TransformExercise1.dir/src/transform_exercise1.cpp.s
.PHONY : src/transform_exercise1.cpp.s

src/transform_exercise2.o: src/transform_exercise2.cpp.o
.PHONY : src/transform_exercise2.o

# target to build an object file
src/transform_exercise2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TransformExercise2.dir/build.make CMakeFiles/TransformExercise2.dir/src/transform_exercise2.cpp.o
.PHONY : src/transform_exercise2.cpp.o

src/transform_exercise2.i: src/transform_exercise2.cpp.i
.PHONY : src/transform_exercise2.i

# target to preprocess a source file
src/transform_exercise2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TransformExercise2.dir/build.make CMakeFiles/TransformExercise2.dir/src/transform_exercise2.cpp.i
.PHONY : src/transform_exercise2.cpp.i

src/transform_exercise2.s: src/transform_exercise2.cpp.s
.PHONY : src/transform_exercise2.s

# target to generate assembly for a file
src/transform_exercise2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TransformExercise2.dir/build.make CMakeFiles/TransformExercise2.dir/src/transform_exercise2.cpp.s
.PHONY : src/transform_exercise2.cpp.s

src/transform_main.o: src/transform_main.cpp.o
.PHONY : src/transform_main.o

# target to build an object file
src/transform_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TransformMain.dir/build.make CMakeFiles/TransformMain.dir/src/transform_main.cpp.o
.PHONY : src/transform_main.cpp.o

src/transform_main.i: src/transform_main.cpp.i
.PHONY : src/transform_main.i

# target to preprocess a source file
src/transform_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TransformMain.dir/build.make CMakeFiles/TransformMain.dir/src/transform_main.cpp.i
.PHONY : src/transform_main.cpp.i

src/transform_main.s: src/transform_main.cpp.s
.PHONY : src/transform_main.s

# target to generate assembly for a file
src/transform_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TransformMain.dir/build.make CMakeFiles/TransformMain.dir/src/transform_main.cpp.s
.PHONY : src/transform_main.cpp.s

src/tugas_persegi.o: src/tugas_persegi.cpp.o
.PHONY : src/tugas_persegi.o

# target to build an object file
src/tugas_persegi.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TugasPersegi.dir/build.make CMakeFiles/TugasPersegi.dir/src/tugas_persegi.cpp.o
.PHONY : src/tugas_persegi.cpp.o

src/tugas_persegi.i: src/tugas_persegi.cpp.i
.PHONY : src/tugas_persegi.i

# target to preprocess a source file
src/tugas_persegi.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TugasPersegi.dir/build.make CMakeFiles/TugasPersegi.dir/src/tugas_persegi.cpp.i
.PHONY : src/tugas_persegi.cpp.i

src/tugas_persegi.s: src/tugas_persegi.cpp.s
.PHONY : src/tugas_persegi.s

# target to generate assembly for a file
src/tugas_persegi.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TugasPersegi.dir/build.make CMakeFiles/TugasPersegi.dir/src/tugas_persegi.cpp.s
.PHONY : src/tugas_persegi.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... BasicLightingExercise1"
	@echo "... BasicLightingExercise2"
	@echo "... BasicLightingExercise3"
	@echo "... BasicLightingExercise4"
	@echo "... BasicLightingMain"
	@echo "... CameraExercise1"
	@echo "... CameraExercise2"
	@echo "... CameraMain"
	@echo "... CoordinateSystemsExercise1"
	@echo "... CoordinateSystemsExercise2"
	@echo "... CoordinateSystemsExercise3"
	@echo "... CoordinateSystemsMain"
	@echo "... Exercise1"
	@echo "... Exercise2"
	@echo "... Exercise3"
	@echo "... LightingMapsExercise1"
	@echo "... LightingMapsExercise2"
	@echo "... LightingMapsExercise3"
	@echo "... LightingMapsMain"
	@echo "... MaterialsExercise1"
	@echo "... MaterialsExercise2"
	@echo "... MaterialsMain"
	@echo "... MultipleLightsExercise1"
	@echo "... OpenGLSetup"
	@echo "... ShaderExercise1"
	@echo "... ShaderExercise2"
	@echo "... ShaderExercise3"
	@echo "... TextureExercise1"
	@echo "... TextureExercise2"
	@echo "... TextureExercise3"
	@echo "... TextureExercise4"
	@echo "... TextureMain"
	@echo "... TransformExercise1"
	@echo "... TransformExercise2"
	@echo "... TransformMain"
	@echo "... TugasPersegi"
	@echo "... src/basic_lighting_exercise1.o"
	@echo "... src/basic_lighting_exercise1.i"
	@echo "... src/basic_lighting_exercise1.s"
	@echo "... src/basic_lighting_exercise2.o"
	@echo "... src/basic_lighting_exercise2.i"
	@echo "... src/basic_lighting_exercise2.s"
	@echo "... src/basic_lighting_exercise3.o"
	@echo "... src/basic_lighting_exercise3.i"
	@echo "... src/basic_lighting_exercise3.s"
	@echo "... src/basic_lighting_exercise4.o"
	@echo "... src/basic_lighting_exercise4.i"
	@echo "... src/basic_lighting_exercise4.s"
	@echo "... src/basic_lighting_main.o"
	@echo "... src/basic_lighting_main.i"
	@echo "... src/basic_lighting_main.s"
	@echo "... src/camera_exercise1.o"
	@echo "... src/camera_exercise1.i"
	@echo "... src/camera_exercise1.s"
	@echo "... src/camera_exercise2.o"
	@echo "... src/camera_exercise2.i"
	@echo "... src/camera_exercise2.s"
	@echo "... src/camera_main.o"
	@echo "... src/camera_main.i"
	@echo "... src/camera_main.s"
	@echo "... src/coordinate_systems_exercise1.o"
	@echo "... src/coordinate_systems_exercise1.i"
	@echo "... src/coordinate_systems_exercise1.s"
	@echo "... src/coordinate_systems_exercise2.o"
	@echo "... src/coordinate_systems_exercise2.i"
	@echo "... src/coordinate_systems_exercise2.s"
	@echo "... src/coordinate_systems_exercise3.o"
	@echo "... src/coordinate_systems_exercise3.i"
	@echo "... src/coordinate_systems_exercise3.s"
	@echo "... src/coordinate_systems_main.o"
	@echo "... src/coordinate_systems_main.i"
	@echo "... src/coordinate_systems_main.s"
	@echo "... src/exercise1.o"
	@echo "... src/exercise1.i"
	@echo "... src/exercise1.s"
	@echo "... src/exercise2.o"
	@echo "... src/exercise2.i"
	@echo "... src/exercise2.s"
	@echo "... src/exercise3.o"
	@echo "... src/exercise3.i"
	@echo "... src/exercise3.s"
	@echo "... src/glad.o"
	@echo "... src/glad.i"
	@echo "... src/glad.s"
	@echo "... src/lighting_maps_exercise1.o"
	@echo "... src/lighting_maps_exercise1.i"
	@echo "... src/lighting_maps_exercise1.s"
	@echo "... src/lighting_maps_exercise2.o"
	@echo "... src/lighting_maps_exercise2.i"
	@echo "... src/lighting_maps_exercise2.s"
	@echo "... src/lighting_maps_exercise3.o"
	@echo "... src/lighting_maps_exercise3.i"
	@echo "... src/lighting_maps_exercise3.s"
	@echo "... src/lighting_maps_main.o"
	@echo "... src/lighting_maps_main.i"
	@echo "... src/lighting_maps_main.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/materials_exercise1.o"
	@echo "... src/materials_exercise1.i"
	@echo "... src/materials_exercise1.s"
	@echo "... src/materials_exercise2.o"
	@echo "... src/materials_exercise2.i"
	@echo "... src/materials_exercise2.s"
	@echo "... src/materials_main.o"
	@echo "... src/materials_main.i"
	@echo "... src/materials_main.s"
	@echo "... src/multiple_lights_exercise1.o"
	@echo "... src/multiple_lights_exercise1.i"
	@echo "... src/multiple_lights_exercise1.s"
	@echo "... src/shader_exercise1.o"
	@echo "... src/shader_exercise1.i"
	@echo "... src/shader_exercise1.s"
	@echo "... src/shader_exercise2.o"
	@echo "... src/shader_exercise2.i"
	@echo "... src/shader_exercise2.s"
	@echo "... src/shader_exercise3.o"
	@echo "... src/shader_exercise3.i"
	@echo "... src/shader_exercise3.s"
	@echo "... src/texture_exercise1.o"
	@echo "... src/texture_exercise1.i"
	@echo "... src/texture_exercise1.s"
	@echo "... src/texture_exercise2.o"
	@echo "... src/texture_exercise2.i"
	@echo "... src/texture_exercise2.s"
	@echo "... src/texture_exercise3.o"
	@echo "... src/texture_exercise3.i"
	@echo "... src/texture_exercise3.s"
	@echo "... src/texture_exercise4.o"
	@echo "... src/texture_exercise4.i"
	@echo "... src/texture_exercise4.s"
	@echo "... src/texture_main.o"
	@echo "... src/texture_main.i"
	@echo "... src/texture_main.s"
	@echo "... src/transform_exercise1.o"
	@echo "... src/transform_exercise1.i"
	@echo "... src/transform_exercise1.s"
	@echo "... src/transform_exercise2.o"
	@echo "... src/transform_exercise2.i"
	@echo "... src/transform_exercise2.s"
	@echo "... src/transform_main.o"
	@echo "... src/transform_main.i"
	@echo "... src/transform_main.s"
	@echo "... src/tugas_persegi.o"
	@echo "... src/tugas_persegi.i"
	@echo "... src/tugas_persegi.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

